export const GET_OTHER_DAYS_MATCHES = 'GET_OTHER_DAYS_MATCHES';
export const GET_OTHER_DAYS_MATCHES_FAIL = 'GET_OTHER_DAYS_MATCHES_FAIL';
export const GET_OTHER_DAYS_MATCHES_SUCCESS = 'GET_OTHER_DAYS_MATCHES_SUCCESS';
