export {default as getTeams} from './GetTeams'
export {default as getData} from './GetLeagues'
export {default as getMatches} from './GetMatches'
export {default as getPreMatches} from './GetPreMatches'
export {default as getAnnouncements} from './GetAnnouncements'
export {default as getTodayMatches} from './GetTodayMatches'
